config/routes.rb
Rails.application.routes.draw do

resources :restaurants  do

resources :reviews
end
end


#only: [ :show, :edit, :index, :new ]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating,presence: true, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, numericality: {only_integer: true}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants= Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant= Restaurant.new
  end

  def create
    restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update

    @restaurant = Restaurant.find(params[:id])

    @restaurant.update(restaurant_params)

    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :adress, :category, :phone_number, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @reviews= Reviews.new
  end

  def create
    reviews.create(review_params)
    redirect_to reviews_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>modifier</h1>

<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :texte %>
  <%= f.text_field :texte%>

  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Les restaurants</h1>


<% @restaurants.each do |restaurant| %>

<%= link_to restaurant.name, restaurant_path(restaurant) %>
<p><%= restaurant.category %></p>



<% end %>

app/views/restaurants/new.html.erb
<h1>ajout de nouveau restaurants/h1>

<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :texte %>
  <%= f.text_field :texte%>

  <%= f.submit %>

  <% end %>

app/views/restaurants/show.html.erb
<h1><%=@restaurant.name %></h1>

<p><%=@restaurant.category %></p>

<%= link_to "modifié", edit_restaurant_path%>
<%= link_to "suppr",restaurant_path, method: :delete %>

app/views/reviews/new.html.erb
<h1>ajout de nouveau restaurants</h1>

<%= form_for(@reviews) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :texte %>
  <%= f.text_field :texte%>

  <%= f.submit %>

  <% end %>

app/views/shared/navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>